return {
   "nvim-treesitter/nvim-treesitter",
   opts = {
      ensure_installed = {
         "bash",
         "c",
         "diff",
         "html",
         "javascript",
         "jsdoc",
         "json",
         "json5",
         "jsonc",
         "lua",
         "luadoc",
         "luap",
         "markdown",
         "markdown_inline",
         "python",
         "query",
         "regex",
         "rust",
         "toml",
         "tsx",
         "typescript",
         "vim",
         "vimdoc",
         "yaml",
      },
   },
}
